spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: "jdbc:h2:mem:dashboard_db"
    driver-class-name: org.h2.Driver
    username: cj
    password: password

mybatis:
    type-aliases-package: com.cj.codingtest.model
    mapper-locations: mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true
      
handlebars:
  cache: false